### ISSUE TITLE
Integration tests after deployment

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild#20]
Initially let us define a list of possible tests that we can do on top of unit tests, once the solution is ready to be deployed.

@MariuszFerdyn since you created different health check scripts, please suggest what can be used. @samarthdd @MaNe2020 we would like your input as QA on what other tests we should include to validate after deployment.

**Comment by samarthdd** [comment]
@GINAGC 

So the idea is once the OVA is created and deployed to AWS/VM,

We need to give a test module or folder which will be having
1. healthchecks 
2. Integration Tests which has tests like rebuild is working or not , pdf has watermark

The above will be included in CI/CD

**Comment by samarthdd** [comment]
Parameters 

IP
Port
username 
password
ICAP-IP (probably)

**Comment by samarthdd** [comment]
@MaNe2020 @GINAGC 
For testing we can use http://3.133.161.191/

Key integration Tests

Part 1 is health check

Part 2 :

1. Check rebuild engine to get response 200 from file
2. Check rebuild engine to get response 200 from xml
3. Test login in 
4. Glasswall processed watermark in xml for pdf

**Comment by MaNe2020** [comment]
@GINAGC @samarthdd as this is about INTEGRATION tests (tests that are executed on modules/components when integrated to verify that they work as expected), we should then focus on testing system as a whole. 
Health check and API calls to rebuild engine do not go under this. 
@GINAGC I was not able to find any architecture diagram about how this solution works. That should be great to have so we can create some meaningful tests.

But in the meantime, I would consider just step 4 from @samarthdd with few modifications.
- Upload PDF file (if just PDFs are supported if not, then upload all kinds of supported files) to http://3.133.161.191/
- Verify file was cleaned (there is no watermark, so verification should be done with new upload)

If we think of file-drop.co.uk as a functional website that we can trust, we can also verify that system works as expected with uploading same file to http://3.133.161.191/ and https://file-drop.co.uk/ and checking the cksumof cleaned files.


![image](https://user-images.githubusercontent.com/70108899/102722131-58de7600-42ff-11eb-8631-da6a724f4daa.png)
