### ISSUE TITLE
Automatic destroy/clean of VM in AWS and VMware

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild#39]
Provide script to delete VMs, the script should consider a deletion criteria defined in a script configuration file to cover a combination of options.

- Delete a VM because of a specific tag.
- Do no delete a VM because of another tag.
- Delete a VM because it has been created since X days.

The target environments for the provided script(s) are: VMware ESX(i) and Amazon EC2

For the VMware code please consider the following repo:
https://github.com/k8-proxy/k8-vmware
And specifically this PR for reference:
https://github.com/k8-proxy/k8-vmware/pull/2

**Comment by naderaly** [comment]
PR for script for auto removing VMs on ESXi with the mentioned criteria above
https://github.com/k8-proxy/k8-vmware/pull/6

Faced a problem on testing on ESXi01 as the creation date of some vms is wrongly configured 
![image](https://user-images.githubusercontent.com/58347752/103905135-e515d900-5106-11eb-8a59-4a5d4a748283.png)

**Comment by GINAGC** [comment]
@naderaly is this still in progress? if not, please move to "Peer Review" status in Pipelines field. Also, since you could not demo, please send a video of the work.

**Comment by GINAGC** [comment]
@naderaly for this one, please send a demo on how this works so far. To get feedback from the team. Thanks

**Comment by naderaly** [comment]
Hello @GINAGC , Dinis requested some fixes for the ESXI script, I will post the demo once fixed.
Also for the AWS script, @samarthdd is the one who has done it
