### ISSUE TITLE
ClientError while importing OVA in AWS

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild#43]
ClientError: Unsupported kernel version 5.4.0-59-generic when importing OVA in AWS.

OVA: https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/vms/SOW-REST/sow-rest.ova

![image (13)](https://user-images.githubusercontent.com/70196799/103743137-148bef00-4ffc-11eb-9ff9-bce56f9ac71c.png)

**Comment by GINAGC** [comment]
Closing issue for this release until we have another update.

**Comment by MariuszFerdyn** [comment]
I did some tesing and I was able to create OVA from this version of Ubuntu and Upload it to AWS.

Ubuntu 18.04.2 LTS | Bionic Beaver

I am still testing other version. Simply AWS import is service that open OVA install some AWS stuff, so simply it will not work with the latest versions of Operating Systems.
