### ISSUE TITLE
Recreate File drop OVA with missed submodules

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild#45]

**Comment by samarthdd** [comment]
OVA side restricutions
Reference:
https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html

1.Operating Systems: Supports till ubuntu 18.04

2.Volume Types and File Systems

3. Cross check limitation from above document

**Comment by GINAGC** [comment]
this is fixed now
