### ISSUE TITLE
Test File Drop OVA deployment in AWS and update documentation

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild#46]

**Comment by samarthdd** [comment]
@GINAGC @NourEddineX 
Issues needs to be resolved.

1. AWS Permission 
2. ClientError: Unsupported kernel version 5.4.0-59-generic"

**Comment by samarthdd** [comment]
OVA side restricutions
Reference: 
https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html

1.Operating Systems: Supports till ubuntu 18.04

2.Volume Types and File Systems

3. Cross check limitation from above document

**Comment by GINAGC** [comment]
Closing issue for this release until we have another update.
