### ISSUE TITLE
Automatic/Scheduled shutdown/Startup of VM in AWS and VMware

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/k8-rebuild#47]
Provide script to shutdown VMs, the script should consider a shutdown/startup criteria defined in a script configuration file to cover a combination of options.

- Shutdown/Startup a VM because of a specific tag.
- Do no shutdown a VM because of another tag.
- More advanced criteria TBD.

The target environments for the provided script(s) are: VMware ESX(i) and Amazon EC2

For the VMware code please consider the following repo:
https://github.com/k8-proxy/k8-vmware

**Comment by belwase** [comment]
@mahnouman  can you explain what you want on "more advanced criteria"
