### ISSUE TITLE
FOLDER TO FOLDER - Zip file not successfully processed

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild#71]
**Issue reported by customer:**

Looks like the latest Glasswall OVA I thought was working successfully wasn’t when I unzip the palantir.zip files after the Glasswall file inspection places it in the ‘output’. **The Glasswall log file says it successfully processed the zip files but it didn’t.**

**1.png picture**
I did an unzip and look at one of the zip files and there are no detections (JSON) files as in the original zip files as Glasswall deleted them during the file inspection processing.

![1](https://user-images.githubusercontent.com/70196799/119138318-0a660c80-ba42-11eb-80fc-db0a2855e0ed.png)

**2.png picture**
Looking at the ‘GlasswallFileProcessingStatus.txt’ file, it’s throwing an error “Input file could not be read”. The first Glasswall OVA that we had the trial license on was working and didn’t have this issue.
![2](https://user-images.githubusercontent.com/70196799/119138341-0e922a00-ba42-11eb-98c2-34f953a971f6.png)

**3.png picture**
![3](https://user-images.githubusercontent.com/70196799/119138352-1356de00-ba42-11eb-8289-a8ef3688ba7e.png)

**OVA:**
https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/vms/k8-rebuild-folder-to-folder/k8-rebuild-fol[…]r-651161dccadd8d3c69bc2f2e0a69fa808e7fc458.ova

**Documentation:**
https://github.com/GW-EAP/ECS-folder-to-folder

**Comment by svf97** [comment]
reproducing the issue with the same OVA:
- error rebuilding palantir.zip files
- the files ended up in the `error` directory 

![image](https://user-images.githubusercontent.com/60857664/119514917-b3c83d80-bd75-11eb-912b-ef47930c3fe6.png)

**Comment by GINAGC** [comment]
Instructions: https://github.com/GW-EAP/ECS-folder-to-folder - need to be updated with the new workflow and also the process overview needs to be updated.
User OVA remains the same one.
Service OVA s3://glasswall-sow-ova/vms/k8-rebuild-folder-to-folder/k8-rebuild-folder-to-folder-001156206238a07939e8231c8950b006a75641da.ova
username: glasswall
password: https://passbolt.glasswallsolutions.com/app/passwords/view/ed5adc62-233b-4cf4-9da4-498bbdbaceed
Please use the test zip files that the customer provided (ping me if you dont have them). The zip files contain tiff and json files. We need to make sure that after the zip file is processed from input to output folder, the tiff files are clean and the json files are intact.

**Comment by GINAGC** [comment]
Fixed on release https://github.com/GW-EAP/ECS-folder-to-folder/releases/tag/v.0.2.1
